apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "laplace.name" . }}-flows
  labels:
    {{- include "laplace.labels" . | nindent 4 }}
data:
  flows.toml: |
    {{- .Values.flows | nindent 4 }}
